# Generated by Django 5.2.7 on 2025-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_item_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="full_ingredients_json",
            field=models.TextField(
                default="[]",
                help_text="Stores the full list of ingredients as a JSON string for display.",
                null=True,
            ),
        ),
    ]
