# Generated by Django 5.2.7 on 2025-10-14 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_recipe_full_ingredients_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="saved_by_users",
            field=models.ManyToManyField(
                blank=True, related_name="saved_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
